### ISSUE TITLE
Doesnt work on SE 2020...

### ISSUE THREAD

**Issue by thekio1984** [tomaszpoliszuk/CameraZoomSlider#1]
Changes nothing on my SE2020 on 13.5, nice tweak idea though looks good..
![E854D3CC-9566-43DE-B57D-A7E8179A0140](https://user-images.githubusercontent.com/31554776/83545507-387fd300-a4f7-11ea-837d-575b90cfb33d.png)

**Comment by tomaszpoliszuk** [comment]
Is SE 2020 have any place where this slider:

![before](https://raw.githubusercontent.com/tomaszpoliszuk/CameraZoomSlider/master/screenshots/before.jpg)

exists in Camera app?

**Comment by thekio1984** [comment]
No, my SE2020 Has only got the slider in my previous image, it doesnt show any different, with or without the tweak anywhere within the camera app.

**Comment by tomaszpoliszuk** [comment]
That's must be because new SE must use different type of UI - this tweak currently just changes how old one looks.
I'm not sure how to implement this in SE but i'll look into it in future (but not soon probably).

Thank you for letting me know :)

**Comment by thekio1984** [comment]
Idk lol & no problem...good luck & hope to use the tweak sometime, ill keep it installed anyway just in case you can sort it!👌👍
